{
 "title": "thedbadmin.com_backrest_mon_deshboard",
 "description": "pgBackRest backup monitoring for thedbadmin.com lab. Uses pgbackrest_exporter metrics via Prometheus.",
 "tags": [
  "pgbackrest",
  "backups"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "stanza",
    "label": "Stanza",
    "query": {
     "query": "label_values(pgbackrest_repo_status, stanza)"
    }
   },
   {
    "name": "repo_key",
    "label": "repo_key",
    "query": {
     "query": "label_values(pgbackrest_repo_status{stanza=~\"$stanza\"}, repo_key)"
    }
   },
   {
    "name": "backup_type",
    "label": "backup_type",
    "query": {
     "query": "label_values(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\"}, backup_type)"
    }
   },
   {
    "name": "backup_name",
    "label": "backup_name",
    "query": {
     "query": "label_values(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\"}, backup_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Stanzas CNT",
     "type": "stat",
     "description": "Count of stanzas.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pgbackrest_stanza_status{stanza=~\"$stanza\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backups CNT",
     "type": "stat",
     "description": "Count of all backups for stanza.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Full backups CNT",
     "type": "stat",
     "description": "Number of full backups.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Diff backups CNT",
     "type": "stat",
     "description": "Number of diff backups.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incr backups CNT",
     "type": "stat",
     "description": "Number of incr backups.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backups with errors CNT",
     "type": "stat",
     "description": "Number of backups with errors.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pgbackrest_backup_error_status{stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stanza status and last backups",
     "type": "table",
     "description": "Current stanza status and information about last backups.",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "pgbackrest_stanza_status{stanza=~\"$stanza\"}"
      },
      {
       "expr": "pgbackrest_backup_since_last_completion_seconds{stanza=~\"$stanza\", backup_type=\"full\"}"
      },
      {
       "expr": "pgbackrest_backup_since_last_completion_seconds{stanza=~\"$stanza\", backup_type=\"diff\"}"
      },
      {
       "expr": "pgbackrest_backup_since_last_completion_seconds{stanza=~\"$stanza\", backup_type=\"incr\"}"
      }
     ]
    },
    {
     "title": "Backups CNT",
     "type": "timeseries",
     "description": "Number of backups by stanza.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by (stanza) (pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Repository status",
     "type": "table",
     "description": "Current repository status.",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "pgbackrest_repo_status{stanza=~\"$stanza\", repo_key=~\"$repo_key\"}"
      }
     ]
    },
    {
     "title": "Average full uncompressed size of the database ",
     "type": "timeseries",
     "description": "Average full uncompressed size of the database  for stanza.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_size_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "WAL archive status",
     "type": "table",
     "description": "Current WAL archive status.",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "pgbackrest_wal_archive_status{stanza=~\"$stanza\", repo_key=~\"$repo_key\"}"
      }
     ]
    },
    {
     "title": "Total size occupied by backups in the repository",
     "type": "timeseries",
     "description": "Total size occupied by backups in the repository by stanza.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (stanza) (pgbackrest_backup_repo_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Number of databases in the last backups",
     "type": "table",
     "description": "Number of databases in the last backups.",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "pgbackrest_backup_last_databases{stanza=~\"$stanza\", backup_type=\"full\"}"
      },
      {
       "expr": "pgbackrest_backup_last_databases{stanza=~\"$stanza\", backup_type=\"diff\"}"
      },
      {
       "expr": "pgbackrest_backup_last_databases{stanza=~\"$stanza\", backup_type=\"incr\"}"
      }
     ]
    },
    {
     "title": "Average number of databases in last backup",
     "type": "timeseries",
     "description": "Average number of databases in last backup.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_last_databases{stanza=~\"$stanza\",backup_type=~\"$backup_type\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    }
   ]
  },
  {
   "title": "General backups info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average full backup duration",
     "type": "timeseries",
     "description": "Average full backup duration for stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"full\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Average diff backup duration",
     "type": "timeseries",
     "description": "Average differential backup duration for stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Average incr backup duration",
     "type": "timeseries",
     "description": "Average incremental backup duration for stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_duration_seconds{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Average size of full backup in the repository",
     "type": "timeseries",
     "description": "Average size occupied by full backup in the repository by stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"full\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Average size of diff backup in the repository",
     "type": "timeseries",
     "description": "Average size occupied by differential backup in the repository by stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"diff\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    },
    {
     "title": "Average size of incr backup in the repository",
     "type": "timeseries",
     "description": "Average size occupied by incremental backup in the repository by stanza.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (stanza) (pgbackrest_backup_repo_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=\"incr\"})",
       "legendFormat": "{{stanza}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed backups info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backup error status",
     "type": "table",
     "description": "Backup error status.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "pgbackrest_backup_error_status{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      }
     ]
    },
    {
     "title": "Backup duration",
     "type": "table",
     "description": "Backup duration.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "pgbackrest_backup_duration_seconds{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      }
     ]
    },
    {
     "title": "Backup size",
     "type": "table",
     "description": "Backup size:\n* databaze size - full uncompressed size of the database;\n* database backup size - amount of data in the database to actually backup;\n* repo backup set size - full compressed files size to restore the database from backup;\n* repo backup size - compressed files size in backup.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pgbackrest_backup_size_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      },
      {
       "expr": "pgbackrest_backup_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      },
      {
       "expr": "pgbackrest_backup_repo_size_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      },
      {
       "expr": "pgbackrest_backup_repo_delta_bytes{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      }
     ]
    },
    {
     "title": "Backup detail info",
     "type": "table",
     "description": "Backup detail info.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "pgbackrest_backup_info{stanza=~\"$stanza\", repo_key=~\"$repo_key\", backup_type=~\"$backup_type\", backup_name=~\"$backup_name\"}"
      }
     ]
    }
   ]
  }
 ]
}