Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9"

  config.vm.define "postgres_server" do |node|
    node.vm.hostname = "postgres-server"

    node.vm.network "public_network",
      dev: "br0",
      mode: "bridge"

    node.vm.network "private_network", ip: "192.168.56.21"

    node.vm.provider "libvirt" do |v|
      v.memory = 8000
      v.cpus   = 4
      v.cpu_mode = "host-passthrough"
    end

    node.vm.provision "shell", path: "pgbackrest/provision.sh"
  end

end
